# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import sympy as sp
import matplotlib.pyplot as plt

t = sp.Symbol('t')

expr = t + 4 / t**2
d_expr = sp.diff(expr, t)

left = 0.5
right = 4
eps = 0.5
steps = 7

critical_points = sp.solve(d_expr, t)
x_exact = float(critical_points[0])

grid = []
h = (right - left) / steps

current = left
for _ in range(steps + 1):
    grid.append(current)
    current += h

values = []
for point in grid:
    values.append(point + 4 / point**2)

min_index = values.index(min(values))
x_approx = grid[min_index]

difference = abs(x_exact - x_approx)
if difference < eps:
    print("loss is", x_exact - x_approx)
else:
    print("shexumy shat a")

plt.plot(grid, values, marker='o')
plt.scatter(x_exact, x_exact + 4 / x_exact**2, s=120, marker='x', label='exact solution')
plt.legend()
plt.grid()
plt.show()