# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt


def f(x):
    return x + 4 / x**2


u = sp.Symbol('u')
formula = u + 4 / u**2
derivative = sp.diff(formula, u)

a = 0.5
b = 4
eps = 0.5
delta = 0.125


roots = sp.solve(derivative, u)
x_star = float(roots[0])


left_border = a
right_border = b

left_history = []
right_history = []

while right_border - left_border > eps:
    mid = (left_border + right_border) / 2
    test1 = mid - delta / 2
    test2 = mid + delta / 2

    if f(test1) <= f(test2):
        right_border = test2
    else:
        left_border = test1

    left_history.append(left_border)
    right_history.append(right_border)

print("a:", left_history)
print("b:", right_history)

x_plot = np.linspace(a, b, 300)
y_plot = [f(val) for val in x_plot]

plt.plot(x_plot, y_plot)
plt.scatter(x_star, f(x_star), color="red")
plt.grid()
plt.show()