# -*- coding: utf-8 -*-
"""Добро пожаловать в Colab!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt


def f(x):
    return x + 4 / x**2


a = 0.5
b = 4
eps = 0.5

phi = (np.sqrt(5) - 1) / 2

left = a
right = b

p1 = right - phi * (right - left)
p2 = left + phi * (right - left)

left_points = []
right_points = []

while right - left > eps:
    y1 = f(p1)
    y2 = f(p2)

    if y1 < y2:
        right = p2
    else:
        left = p1

    left_points.append(left)
    right_points.append(right)

    p1 = right - phi * (right - left)
    p2 = left + phi * (right - left)

print("a:", left_points)
print("b:", right_points)

x_result = (left + right) / 2
y_result = f(x_result)

print("xmin =", x_result)
print("f(xmin) =", y_result)

x_draw = np.linspace(a, b, 300)
y_draw = [f(num) for num in x_draw]

plt.plot(x_draw, y_draw)
plt.scatter(x_result, y_result, color='red')
plt.grid()
plt.show()